---
title: "HW 12: Dates"
author: "Dylan Klingeman"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***
## Libraries
```{r}
library(tidyverse)
library(here)
library(lubridate)
```

```{r}
source(here("scripts", "my_functions.R"))
```

### Part 1: Play Date

```{r}
birth_date <- "04/03/1996"

# Elizabeth Garret Anderson was the first female physician
anderson <- "9 June 1836"

# Mary Anning discovered the first complete Plesiosaur fossil, 
# and other important Jurassic fossils
anning <-  "1799/05/21"

# Alice Augusta Ball was a chemist who developed the
# first injectable treatment for leprosy.
ball <- "July 24, 1892"

# Sylvia Earle was the first chieft scientist at NOAA
earle <- "August, 30 (1935)"

# Rosalind Franklin used x-ray diffraction to 
# discover DNA structure. Watson and Crick claimed credit.
franklin <- "25th of July, 1920"

# Ester Lederberg was the first to discover that viruses 
# infect bacteria. Led to discovery of lambda bacteriophage
lederberg <- "December 18, 1922"

# Barbara McClintock discovered transposable elements (jumping genes),
# and developed staining techniques to study chromosomes
mcclintock <- "16061902"

# Let's also remember a dream
mlk_birth <- "1/15/29"
mlk_dream <- "1963 August 28"
```

## 1: 

```{r}
my_birth_date <- mdy(birth_date)
my_birth_date

anderson_birth_date <- dmy(anderson)
anderson_birth_date

anning_birth_date <- ymd(anning)
anning_birth_date

ball_birth_date <- mdy(ball)
ball_birth_date

earle_birth_date <- mdy(earle)
earle_birth_date

franklin_birth_date <- dmy(franklin)
franklin_birth_date

lederberg_birth_date <- mdy(lederberg)
lederberg_birth_date

mcclintock_birth_date <- dmy(mcclintock)
mcclintock_birth_date

mlk_birth_date <- mdy("01/15/1929")
mlk_birth_date

mlk_dream_date <- ymd(mlk_dream)
mlk_dream_date
```

# This code chunk inserts all of the birthdays from some important figures, as well as the i have a dream speech. 

#

## 2. 

# Fixed the MLK birth date above. 

#

## 3. 
```{r}
wday(my_birth_date, label = TRUE, abbr = FALSE)
```

#

## 4. 

```{r}
updated_my_birthday <- update(my_birth_date$year == 'Y')
```

# I cannot find this one even by googling it, will come back to it. 

## 5. 

```{r}
updated_my_birthday <- update(my_birth_date, year=2525, month = 4, day = 03)
wday(updated_my_birthday, label = TRUE, abbr = TRUE)

year(updated_my_birthday) - year(my_birth_date)

```

# 

## 6. 

```{r}
day(ball_birth_date) - day(anderson_birth_date) 
```

# This code chunk subtracts the birthdates between ball and anderson. 

#

## 7. 

```{r}
(mlk_dream_date - mlk_birth_date)
```

# 8. 

```{r}
birth_dates <- c(my_birth_date, anderson_birth_date, anning_birth_date, ball_birth_date, earle_birth_date, franklin_birth_date, lederberg_birth_date, mcclintock_birth_date, mlk_birth_date)
names(dates) <- c('Klingeman', 'Anderson', 'Anning', 'Ball', 'Earle', 'Franklin', 'Lederberg', 'McClintock', 'King')

leap_year(birth_dates)

birth_dates - my_birth_date
```

#

### Part 2: Wrangling and plotting with dates