### Chapter 14 Strings

# 14.2 String basics

```{r}
string1 <- "This is a string"
string2 <- 'If I want to include a "quote" inside a string, i use single quotes'
```


```{r}
string1
string2
```

```{r}
double_quote <- "\"" # or '"'
double_quote

single_quote <- '\'' # or "'"
single_quote
```

```{r}
x <- c("\"", "\\")
x
writeLines(x)
```

# 14.2.1 String Length

```{r}
str_length(c("a", "R for data science", NA))
```
# 14.2.2

```{r}
str_c("x", "y")

str_c("x", "y", "z")
```

```{r}
str_c("x", "y", sep = ",")
```

```{r}
x <- c("abc", NA)
str_c("|-", x, "-|")

str_c("|-", str_replace_na(x), "-|")
```

```{r}
str_c("prefix-", c("a", "b", "c"), "-suffix")
```

```{r}
name <- "Hadley"
time_of_day <- "morning"
birthday <- TRUE

str_c(
  "Good", time_of_day, " ", name, 
  if (birthday) " and HAPPY BIRTHDAY", 
  "."
)
```

# 14.2.3 Subsetting strings

```{r}
x <- c("Apple", "Banana", "Pear")
       str_sub(x, 1, 3)
       
# negative numbers coutn backwards from end
       
       str_sub(x, -3, -1)
       
       str_sub("a", 1, 5)
```

```{r}
str_sub(x, 1, 1) <- str_to_lower(str_sub(x, 1, 1))
x
```

# 14.2.4 Locales

```{r}
# Turkish has two i's: with and without a dot, and it 
# has a different rule for capitalising them: 
str_to_upper(c("i", "ı"))

str_to_upper(c("i", "ı"), locale = "tr")
```

```{r}
x <- c("apple", "eggplant", "banana")

str_sort(x, locale = "en") # English

str_sort(x, locale = "haw") # Hawaiian
```

# 14.3

```{r}
library(tidyverse)
```


```{r}
x <- c("apple", "banana", "pear")
str_view(x, "an")
```

```{r}
str_view(x, ".a.")
```

```{r}
dot <- "\\."


writeLines(dot)

str_view(c("abc", "a.c", "bef"), "a\\.c")
```

```{r}
x <- "a\\b"

writeLines(x)

str_view(x, "\\\\")
```

# 14.3.2 Anchors-