---
title: "HW 13: Strings and things"
author: "Dylan Klingeman"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(ggthemes)
library(gghighlight)
```

### Part 1: DNA strings

```{r}
gliadin_data <- read_lines(here("data", "beta_gliadin.txt"), skip = 1)
gliadin_data
```

# Imports the beta gliadin dataset and removes the first line. 

```{r}
gliadin_wrangled <- str_replace_all(gliadin_data, c("\\d" = "", "\\s" = "")) %>%  # removes all digits and spaces
  
str_c(collapse = "") %>% # collapses into a single string

str_to_upper() # converts to uppercase letters

str_length(gliadin_wrangled) # measures string length

gliadin_wrangled
```

# Put all the steps into one block to save space. Will try to do this as much as possible going forward. 

```{r}
str_count(gliadin_wrangled, "[A.C.T.G]")   # All are A, C, T, G
str_count(gliadin_wrangled, "ATG") # 66 matches
str_count(gliadin_wrangled, "TGA|TAA") # 99 matches
```

# Counts totals, had to use only one set of quotations to make the final line work. 

```{r}
caat_box <- "CCAAT"
tata_box <- "CTATAA"

str_count(gliadin_wrangled, caat_box) # 4 matches
str_count(gliadin_wrangled, tata_box) # 1 match

caat_seq <- "CCAAT.{100,150}ATG" # like in 14.3.4
str_count(gliadin_wrangled, caat_seq) # 2 matches

tata_seq <- "CTATAA.{50,100}ATG" # 1 match
str_count(gliadin_wrangled, tata_seq)
```

# tata seq was returning 0 matches, fixed typo from "CATATAA" -> "CTATAA"

```{r}
caat_seqs_all <- str_extract_all(gliadin_wrangled, caat_seq, simplify = TRUE) # saves all caat sequences

caat_seqs_all
str_length(caat_seqs_all) # sequence 1 is 139, sequence 2 is 148. 

str_which(caat_seqs_all, tata_seq) # sequence1 contains the tata sequence. 

promoter <- str_subset(caat_seqs_all, tata_seq) # prints the entire string 1.
promoter
```

# 

### Part 2: Ants
